global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['node-app:3000']
  - job_name: 'travelling-app'
    scheme: https
    static_configs:
      - targets: ['travelling-site.onrender.com']